include(":base", ":navigation", ":ui", ":viewmodel")
include(":local", ":remote")
include(":data")
include(":app")
include(":details", ":discover", ":schedule", ":search", ":settings", ":shows", ":watchlist")
