include(":base", ":navigation", ":viewmodel")
include(":local", ":remote", ":ui")
include(":data")
include(":app")
include(":details", ":discover", ":schedule", ":search", ":settings", ":shows", ":watchlist")
