version: 2.1

config: &config
  working_directory: ~/workspace
  docker:
    - image: circleci/android:api-29
  environment:
    GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.workers.max=2 -Djava.util.concurrent.ForkJoinPool.common.parallelism=2 -Dkotlin.incremental=false"
    TERM: dumb

commands:
  restore:
    description: Restore Workspace
    steps:
      - checkout
      - attach_workspace:
          at: ~/workspace
      - restore_cache:
          keys:
            - gradle-{{ .Environment.CIRCLE_SHA1 }}
  save:
    description: Save Workspace
    steps:
      - save_cache:
          key: gradle-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/.gradle/
      - persist_to_workspace:
          root: ~/workspace
          paths:
            - ./*/build

jobs:
  build_debug:
    <<: *config
    steps:
      - checkout
      - run:
          name: Download Dependencies
          command: ./gradlew dependencies
      - run:
          name: Build Debug Apk and Bundle
          command: ./gradlew assembleDebug bundleDebug
      - store_artifacts:
          path: app/build/outputs
          destination: outputs
      - save
  build_release:
    <<: *config
    steps:
      - restore
      - run:
          name: Build Release Apk and Bundle
          command: ./gradlew assembleRelease bundleRelease
      - store_artifacts:
          path: app/build/outputs
          destination: outputs
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - save
  check:
    <<: *config
    steps:
      - restore
      - run:
          name: Check App and Dependencies
          command: ./gradlew spotlessCheck dependencyUpdates
      - store_artifacts:
          path: build/dependencyUpdates
          destination: dependencyUpdates
      - save

workflows:
  version: 2
  build_deploy:
    jobs:
      - build_debug
      - build_release:
          requires:
            - build_debug
      - check:
          requires:
            - build_debug