build:
  maxIssues: 0
complexity:
  TooManyFunctions:
    thresholdInFiles: 15
    thresholdInClasses: 15
    thresholdInInterfaces: 15
    thresholdInObjects: 15
    thresholdInEnums: 15
style:
  MaxLineLength:
    maxLineLength: 150
formatting:
  active: true
  android: false
  MaximumLineLength:
    active: false
