build:
  maxIssues: 1
complexity:
  TooManyFunctions:
    thresholdInFiles: 15
    thresholdInClasses: 15
    thresholdInInterfaces: 15
    thresholdInObjects: 15
    thresholdInEnums: 15
style:
  MaxLineLength:
    maxLineLength: 150

