#!/bin/bash

BUNDLE_VERSION="0.11.0"
BUNDLE_TOOL="https://github.com/google/bundletool/releases/download/${BUNDLE_VERSION}/bundletool-all-${BUNDLE_VERSION}.jar"
ARTIFACTS="artifacts"

function create_apk() {
  variant=${1}
  store_file=".signing/app-${variant}.jks"
  store_password=${2}
  key_alias=${3}
  key_password=${4}

  java -jar bundletool-all-${BUNDLE_VERSION}.jar build-apks \
    --bundle=app/build/outputs/bundle/${variant}/app-${variant}.aab \
    --output=app/build/outputs/apk/${variant}/app-${variant}.apks \
    --mode=universal \
    --ks=${store_file} \
    --ks-pass=pass:${store_password} \
    --ks-key-alias=${key_alias} \
    --key-pass=pass:${key_password}

  unzip app/build/outputs/apk/${variant}/app-${variant}.apks -d app/build/outputs/apk/${variant}/
  mv app/build/outputs/apk/${variant}/universal.apk ${ARTIFACTS}/tv-${variant}.apk
}

function main() {
  mkdir -p ${ARTIFACTS}
  wget ${BUNDLE_TOOL}
  create_apk debug android debug android
  create_apk release ${TV_RELEASE_STORE_PASSWORD} ${TV_RELEASE_KEY_ALIAS} ${TV_RELEASE_KEY_PASSWORD}
}

main