#!/bin/bash

TITLE="Latest"
BODY="Latest Master Build"
TAG="LATEST"
PATH="./artifacts"

function main() {
  go get github.com/tcnksm/ghr
  ghr -t ${GITHUB_TOKEN} /
      -u ${CIRCLE_PROJECT_USERNAME} /
      -r ${CIRCLE_PROJECT_REPONAME} /
      -c ${CIRCLE_SHA1} /
      -n ${TITLE} /
      -b ${BODY} /
      -delete /
      ${TAG} ${PATH}
}

main