#!/bin/bash

function main() {
  go get github.com/tcnksm/ghr
  ghr -t ${GITHUB_TOKEN} \
      -u ${CIRCLE_PROJECT_USERNAME} \
      -r ${CIRCLE_PROJECT_REPONAME} \
      -c ${CIRCLE_SHA1} \
      -n "Latest" \
      -b "Latest Master Build" \
      -delete \
      LATEST ./artifacts
}

 main 